package ly.generalassemb.drewmahrt.gsonexample;

import android.content.Context;
import android.net.ConnectivityManager;
import android.net.NetworkInfo;
import android.os.AsyncTask;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.ListView;
import android.widget.TextView;
import android.widget.Toast;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.ArrayList;

import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;

public class MainActivity extends AppCompatActivity {

    //TODO: Insert your API Key into the URL
    private static String mUrl = "http://api.walmartlabs.com/v1/items?apiKey=YOURAPIKEY&upc=035000521019";

    private WalmartAsyncTask mTask;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);


        ConnectivityManager connMgr = (ConnectivityManager) getSystemService(Context.CONNECTIVITY_SERVICE);
        NetworkInfo networkInfo = connMgr.getActiveNetworkInfo();
        if (networkInfo != null && networkInfo.isConnected()) {
            if (mTask != null && (mTask.getStatus() != AsyncTask.Status.FINISHED)) {
                mTask.cancel(true);
            }
            mTask = new WalmartAsyncTask();
            mTask.execute(mUrl);
        } else {
            Toast.makeText(MainActivity.this, "No network connection detected", Toast.LENGTH_SHORT).show();
        }
    }

    public class WalmartAsyncTask extends AsyncTask<String, Void, Void> {

        //TODO: change the return type from void to a new class representing the API data
        @Override
        protected Void doInBackground(String... params) {

            OkHttpClient client = new OkHttpClient();

            Request request = new Request.Builder()
                    .url(params[0])
                    .build();

            try {
                Response response = client.newCall(request).execute();

                //TODO: use GSON to generate objects from the JSON response
                //response.body().string();

            } catch (IOException e) {
                e.printStackTrace();
            }

            //TODO: return an object representing the data returned by the API so onPostExecute() can use it
            return null;
        }

        @Override
        protected void onPostExecute(Void aVoid) {
            super.onPostExecute(aVoid);

            //TODO: update the UI using the objects generated by GSON
        }
    }
}
